polls/urls.py
from django.urls import path, include
from rest_framework import routers

from polls import views
from polls.views import QuestionsView, IndexView

router = routers.DefaultRouter()
router.register(r"questions", views.QuestionViewSet, basename="question")

app_name = "polls"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("questions/", QuestionsView.as_view(), name="questions"),
    path("questions/<str:type>/", QuestionsView.as_view(), name="my-questions"),
    path("api/", include(router.urls)),
]

polls_django_app/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('polls/', permanent=True)),
    path('polls/', include('polls.urls')),
    path('accounts/login/', LoginView.as_view(template_name='admin/login.html')),
    path('accounts/logout/', LogoutView.as_view()),

    path('api-auth/', include('rest_framework.urls'))
]

polls/models.py
from django.contrib.auth.models import User, Group
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def has_permission(self, user, permission_type):
        try:
            permission = QuestionPermission.objects.get(question=self, user=user)
            if permission_type == "view":
                return permission.can_view
            elif permission_type == "edit":
                return permission.can_edit
        except QuestionPermission.DoesNotExist:
            return False

        # check if user's group has permission
        user_groups = user.groups.all()
        group_permissions = QuestionPermission.objects.filter(question=self, group__in=user_groups)
        if group_permissions.exists():
            if permission_type == "view":
                return group_permissions.filter(can_view=True).exists()
            elif permission_type == "edit":
                return group_permissions.filter(can_edit=True).exists()
        return False


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices', blank=True)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def has_permission(self, user, permission_type):
        # check question's permission
        return self.question.has_permission(user, permission_type)


class QuestionPermission(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='permissions')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    can_view = models.BooleanField(default=False)
    can_edit = models.BooleanField(default=False)

    class Meta:
        unique_together = ['question', 'user', 'group']

polls/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView
from rest_framework import viewsets

from polls.models import Question, QuestionPermission
from polls.permissions import QuestionPermissionMixin
from polls.serializers import QuestionSerializer


# Create your views here.

@login_required
def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


class QuestionViewSet(QuestionPermissionMixin, viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer
    lookup_field = 'id'

    def get_queryset(self):
        return Question.objects.filter(pk__in=[
            question_permission.question_id for question_permission in
            QuestionPermission.objects.filter(user=self.request.user)
        ])


class IndexView(TemplateView):
    template_name = "index.html"


class QuestionsView(TemplateView):
    template_name = "questions.html"
    queryset = Question.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.kwargs.get('type') == 'my':
            self.queryset = self.queryset.filter(pk__in=[
                question_permission.question_id for question_permission in
                QuestionPermission.objects.filter(user=self.request.user)
            ])

        context['questions'] = self.queryset
        context['type'] = self.kwargs.get('type')
        return context

polls/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Polls</title>
</head>
<body>
<div style="padding-bottom: 20px">
<form method="post" action="/accounts/logout/">
    {% csrf_token %}
    <button type="submit">Logout</button>
</form>
</div>
{% block content %}
{% endblock %}
</body>
</html>
<style>
    html {
 /* Base styles go here */
 font: 14px/1.5 Arial, sans-serif;
 background: #ffffff;
}

body {
 background: #ffffff;
 padding: 30px;
 width: 920px;
 margin: 0 auto;
}
</style>

polls/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <a href="{% url 'polls:questions' %}">Questions list</a>
    </div>
    <div>
        <a href="{% url 'polls:my-questions' type='my' %}">My questions</a>
    </div>
{% endblock %}

polls/templates/questions.html
{% extends 'base.html' %}
{% block content %}
    {% if type == 'my' %}
        <h3>My Questions</h3>
    {% else %}
        <h3>All Questions</h3>
    {% endif %}

    <ul>
        {% for question in questions %}

            <li><span class="left-value">{{ question.question_text }}</span><span
                    class="right-value">{{ question.pub_date }}</span></li>

        {% endfor %}
    </ul>
{% endblock %}
<style>
    ul {
        list-style-type: none;
        padding: 0;
        margin: 0;
        width: 300px;
    }

    li {
        display: flex;
        justify-content: space-between;
        padding: 8px;
        border-bottom: 1px solid #ccc;
    }

    .left-value {
        /* Left-aligned by default */
    }

    .right-value {
        /* Flex alignment pushes it to the right */
    }
</style>